language: python

# The docker image will have 3.7, so this is fine
python:
  - '3.6'

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "flake8 && python manage.py test"
